### ISSUE TITLE
Preprocessor Macroの調査

### ISSUE THREAD

**Issue by testusuke** [TNCT-Mechatech/SerialBridge#4]
現在のライブラリはマルチプラットフォームでの使用を想定している。そのため、不要なファイルを読み込んでしまう事が問題点となる。
解決策として、各プラットフォーム(Linux,Arduino,Mbed, etc.)のPreprocessorマクロを指定することが妥当だろう。

**Comment by TaiyouKomazawa** [comment]
Arduinoの方での調査
`#ifdef ARDUINO` を利用することで、Arduinoのビルダのみに認識され、プラットフォームの分離を図ることができるようです。

**Comment by TaiyouKomazawa** [comment]
mbedの方での調査
`#ifdef MBED_MAJOR_VERSION` がmbed.hより前に定義されることが分かったので使ってみました。
オンラインコンパイラでは問題なく読み込めました。mbed studioのほうは環境を入れていないのでお任せします。

**Comment by TaiyouKomazawa** [comment]
mbedに関する調査について修正
predifined macroはarm gcc由来のものである`__arm__`を用いることに変更しました。
