### ISSUE TITLE
mbed 6.0への対応

### ISSUE THREAD

**Issue by TaiyouKomazawa** [TNCT-Mechatech/SerialBridge#8]
ソース: https://os.mbed.com/docs/mbed-os/v6.14/apis/index.html#deprecated-apis

どうやら、`MbedHardwareSerial`の実装は現状のバージョンでは使用できないSerial APIが用いられています。
よって、現状の新規プロジェクトではコンパイルエラーが発生します。

**Comment by TaiyouKomazawa** [comment]
今回のシステムの要件を満たす場合、公式が提供しているバッファ付シリアルを使用するほうが良いかと思います。
https://os.mbed.com/docs/mbed-os/v6.14/apis/serial-uart-apis.html

**Comment by testusuke** [comment]
STM32 Nucleo F303K8などといった小型マイコンにはmbed-os5,6が搭載できないためSerialを使っていました。

**Comment by testusuke** [comment]
環境ごとにドライバーを用意するのはどうでしょうか？

**Comment by TaiyouKomazawa** [comment]
両立する形で改良を行いました。
